name: BobApp Workflow
run-name: ${{ github.actor }} is using Bobapp Workflow
on:
  pull_request:
    branches: [ "main" ]
  push: 
    branches: [ "achmoye-patch-1" ]
    
jobs: 

  Frontend-Angular:
    timeout-minutes: 10
    name: Frontend-Angular
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'front'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      #Added for CI/CD workflow 
      - name: npm dependencies
        run: npm install  
        
      #Frontend tests and coverage
      - name: Running tests 
        run: npm test -- --watch=false --code-coverage --browsers=ChromeHeadless
        
      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: Test Reports
          path: front/coverage/
        
        
  Backend-Java:    
    timeout-minutes: 10
    name: Backend-java
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'back'
    steps:
      #Backend tests and coverage
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
            java-version: 1.11
      - name: Build with Maven
        working-directory: ./back
        run: mvn -B package --file pom.xml
      - name: Test with Maven
        working-directory: ./back
        run: mvn -B test --file pom.xml
        
        
  Jacoco-coverage:
     timeout-minutes: 10
     runs-on: ubuntu-latest
     steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: back

      - name: Run tests and generate JaCoCo report
        run: mvn -B clean verify
        working-directory: back

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: back/target/site/jacoco
          
          
  Docker-push:
    timeout-minutes: 10
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: achmoye/repo-test
      
      - name: Build and push Docker image (front)
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Build and push Docker image (back)
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
