name: Build, Test & Coverage
run-name: ${{ github.actor }} is testing The application ğŸš€
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    name: Build, Test and coverage Backend
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version : '17'
          distribution: 'temurin'
      - name: Checkout
        uses: actions/checkout@v3
      - name : move to backend folder
        run: cd back
      - name: Test & Coverage back
        run: mvn -B -U verify
      - run: echo "ğŸ This job's status is ${{ job.status }}."

