name: CI/CD
run-name: ${{ github.actor }} is working on GitHub Actions!
on: [push]

jobs:
  frontendTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Front-end Dependencies
        run: npm install
        working-directory: ./front

      - name: Run Front-end Tests
        run: npm run test:prod
        working-directory: ./front

      - name: Upload Karma Report
        uses: actions/upload-artifact@v3
        with:
          name: karma-report
          path: ./front/coverage

  backendTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Build with Maven
        run: mvn -B package --file ./pom.xml
        working-directory: ./back

      - name: Test with Maven
        run: mvn -B clean test
        working-directory: ./back

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: ./back/target/site/jacoco

  sonarQubeAnalysisFrontend:
    runs-on: ubuntu-latest
    needs: frontendTests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: Set working directory to frontend
        run: echo "Setting working directory to frontend"
        working-directory: ./front
      - name: SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}



  sonarQubeAnalysisBackend:
    runs-on: ubuntu-latest
    needs: backendTests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: bobapp
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        working-directory: ./back

  build:
    runs-on: ubuntu-latest
    needs: [backendTests, frontendTests, sonarQubeAnalysisFrontend, sonarQubeAnalysisBackend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_EMAIL }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Back-end
        uses: docker/build-push-action@v5
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:latest

      - name: Build and Push Front-end
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest
