name: Tests and Code Coverage Back
on:
  push:
    branches: [ "Develop" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Launching Mvn Test on Backend source code"
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean test --file back/pom.xml
      - run: echo "üçèMvn Test's status is ${{ job.status }}."
      - name: Add coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          pass-emoji: üçè
          fail-emoji: ‚ùå
          debug-mode: false
      - run: echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
      - run: echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
      - name: Commit Code Coverage Report
        run: |
          git config --global user.email "cedh@posteo.net"
          git config --global user.name "cedh44"
          git add .
          git commit -m "Add jacoco coverage report"
          git push
